// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
)

// ReferralCommissionUpdate is the builder for updating ReferralCommission entities.
type ReferralCommissionUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdate) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralCommissionUpdate) SetInviterID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableInviterID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralCommissionUpdate) AddInviterID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetDownlineID sets the "downline_id" field.
func (_u *ReferralCommissionUpdate) SetDownlineID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetDownlineID()
	_u.mutation.SetDownlineID(v)
	return _u
}

// SetNillableDownlineID sets the "downline_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableDownlineID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetDownlineID(*v)
	}
	return _u
}

// AddDownlineID adds value to the "downline_id" field.
func (_u *ReferralCommissionUpdate) AddDownlineID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddDownlineID(v)
	return _u
}

// SetTier sets the "tier" field.
func (_u *ReferralCommissionUpdate) SetTier(v int8) *ReferralCommissionUpdate {
	_u.mutation.ResetTier()
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableTier(v *int8) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// AddTier adds value to the "tier" field.
func (_u *ReferralCommissionUpdate) AddTier(v int8) *ReferralCommissionUpdate {
	_u.mutation.AddTier(v)
	return _u
}

// SetSourceRequestID sets the "source_request_id" field.
func (_u *ReferralCommissionUpdate) SetSourceRequestID(v string) *ReferralCommissionUpdate {
	_u.mutation.SetSourceRequestID(v)
	return _u
}

// SetNillableSourceRequestID sets the "source_request_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableSourceRequestID(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetSourceRequestID(*v)
	}
	return _u
}

// SetBaseAmount sets the "base_amount" field.
func (_u *ReferralCommissionUpdate) SetBaseAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetBaseAmount()
	_u.mutation.SetBaseAmount(v)
	return _u
}

// SetNillableBaseAmount sets the "base_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableBaseAmount(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetBaseAmount(*v)
	}
	return _u
}

// AddBaseAmount adds value to the "base_amount" field.
func (_u *ReferralCommissionUpdate) AddBaseAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddBaseAmount(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *ReferralCommissionUpdate) SetRate(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableRate(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *ReferralCommissionUpdate) AddRate(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddRate(v)
	return _u
}

// SetCommissionAmount sets the "commission_amount" field.
func (_u *ReferralCommissionUpdate) SetCommissionAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetCommissionAmount()
	_u.mutation.SetCommissionAmount(v)
	return _u
}

// SetNillableCommissionAmount sets the "commission_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableCommissionAmount(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetCommissionAmount(*v)
	}
	return _u
}

// AddCommissionAmount adds value to the "commission_amount" field.
func (_u *ReferralCommissionUpdate) AddCommissionAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddCommissionAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralCommissionUpdate) SetStatus(v string) *ReferralCommissionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableStatus(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ReferralCommissionUpdate) SetSettledAt(v time.Time) *ReferralCommissionUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableSettledAt(v *time.Time) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *ReferralCommissionUpdate) ClearSettledAt() *ReferralCommissionUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetSettledByAdminID sets the "settled_by_admin_id" field.
func (_u *ReferralCommissionUpdate) SetSettledByAdminID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetSettledByAdminID()
	_u.mutation.SetSettledByAdminID(v)
	return _u
}

// SetNillableSettledByAdminID sets the "settled_by_admin_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableSettledByAdminID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetSettledByAdminID(*v)
	}
	return _u
}

// AddSettledByAdminID adds value to the "settled_by_admin_id" field.
func (_u *ReferralCommissionUpdate) AddSettledByAdminID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddSettledByAdminID(v)
	return _u
}

// ClearSettledByAdminID clears the value of the "settled_by_admin_id" field.
func (_u *ReferralCommissionUpdate) ClearSettledByAdminID() *ReferralCommissionUpdate {
	_u.mutation.ClearSettledByAdminID()
	return _u
}

// SetSettledNote sets the "settled_note" field.
func (_u *ReferralCommissionUpdate) SetSettledNote(v string) *ReferralCommissionUpdate {
	_u.mutation.SetSettledNote(v)
	return _u
}

// SetNillableSettledNote sets the "settled_note" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableSettledNote(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetSettledNote(*v)
	}
	return _u
}

// ClearSettledNote clears the value of the "settled_note" field.
func (_u *ReferralCommissionUpdate) ClearSettledNote() *ReferralCommissionUpdate {
	_u.mutation.ClearSettledNote()
	return _u
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdate) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralCommissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralCommissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdate) check() error {
	if v, ok := _u.mutation.SourceRequestID(); ok {
		if err := referralcommission.SourceRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "source_request_id", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.source_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralCommissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DownlineID(); ok {
		_spec.SetField(referralcommission.FieldDownlineID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownlineID(); ok {
		_spec.AddField(referralcommission.FieldDownlineID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(referralcommission.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedTier(); ok {
		_spec.AddField(referralcommission.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.SourceRequestID(); ok {
		_spec.SetField(referralcommission.FieldSourceRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseAmount(); ok {
		_spec.SetField(referralcommission.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseAmount(); ok {
		_spec.AddField(referralcommission.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(referralcommission.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(referralcommission.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionAmount(); ok {
		_spec.AddField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(referralcommission.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(referralcommission.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledByAdminID(); ok {
		_spec.SetField(referralcommission.FieldSettledByAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettledByAdminID(); ok {
		_spec.AddField(referralcommission.FieldSettledByAdminID, field.TypeInt64, value)
	}
	if _u.mutation.SettledByAdminIDCleared() {
		_spec.ClearField(referralcommission.FieldSettledByAdminID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SettledNote(); ok {
		_spec.SetField(referralcommission.FieldSettledNote, field.TypeString, value)
	}
	if _u.mutation.SettledNoteCleared() {
		_spec.ClearField(referralcommission.FieldSettledNote, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralCommissionUpdateOne is the builder for updating a single ReferralCommission entity.
type ReferralCommissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralCommissionUpdateOne) SetInviterID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableInviterID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralCommissionUpdateOne) AddInviterID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetDownlineID sets the "downline_id" field.
func (_u *ReferralCommissionUpdateOne) SetDownlineID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetDownlineID()
	_u.mutation.SetDownlineID(v)
	return _u
}

// SetNillableDownlineID sets the "downline_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableDownlineID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetDownlineID(*v)
	}
	return _u
}

// AddDownlineID adds value to the "downline_id" field.
func (_u *ReferralCommissionUpdateOne) AddDownlineID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddDownlineID(v)
	return _u
}

// SetTier sets the "tier" field.
func (_u *ReferralCommissionUpdateOne) SetTier(v int8) *ReferralCommissionUpdateOne {
	_u.mutation.ResetTier()
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableTier(v *int8) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// AddTier adds value to the "tier" field.
func (_u *ReferralCommissionUpdateOne) AddTier(v int8) *ReferralCommissionUpdateOne {
	_u.mutation.AddTier(v)
	return _u
}

// SetSourceRequestID sets the "source_request_id" field.
func (_u *ReferralCommissionUpdateOne) SetSourceRequestID(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetSourceRequestID(v)
	return _u
}

// SetNillableSourceRequestID sets the "source_request_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableSourceRequestID(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetSourceRequestID(*v)
	}
	return _u
}

// SetBaseAmount sets the "base_amount" field.
func (_u *ReferralCommissionUpdateOne) SetBaseAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetBaseAmount()
	_u.mutation.SetBaseAmount(v)
	return _u
}

// SetNillableBaseAmount sets the "base_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableBaseAmount(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetBaseAmount(*v)
	}
	return _u
}

// AddBaseAmount adds value to the "base_amount" field.
func (_u *ReferralCommissionUpdateOne) AddBaseAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddBaseAmount(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *ReferralCommissionUpdateOne) SetRate(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableRate(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *ReferralCommissionUpdateOne) AddRate(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddRate(v)
	return _u
}

// SetCommissionAmount sets the "commission_amount" field.
func (_u *ReferralCommissionUpdateOne) SetCommissionAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetCommissionAmount()
	_u.mutation.SetCommissionAmount(v)
	return _u
}

// SetNillableCommissionAmount sets the "commission_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableCommissionAmount(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetCommissionAmount(*v)
	}
	return _u
}

// AddCommissionAmount adds value to the "commission_amount" field.
func (_u *ReferralCommissionUpdateOne) AddCommissionAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddCommissionAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralCommissionUpdateOne) SetStatus(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableStatus(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ReferralCommissionUpdateOne) SetSettledAt(v time.Time) *ReferralCommissionUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableSettledAt(v *time.Time) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *ReferralCommissionUpdateOne) ClearSettledAt() *ReferralCommissionUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetSettledByAdminID sets the "settled_by_admin_id" field.
func (_u *ReferralCommissionUpdateOne) SetSettledByAdminID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetSettledByAdminID()
	_u.mutation.SetSettledByAdminID(v)
	return _u
}

// SetNillableSettledByAdminID sets the "settled_by_admin_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableSettledByAdminID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetSettledByAdminID(*v)
	}
	return _u
}

// AddSettledByAdminID adds value to the "settled_by_admin_id" field.
func (_u *ReferralCommissionUpdateOne) AddSettledByAdminID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddSettledByAdminID(v)
	return _u
}

// ClearSettledByAdminID clears the value of the "settled_by_admin_id" field.
func (_u *ReferralCommissionUpdateOne) ClearSettledByAdminID() *ReferralCommissionUpdateOne {
	_u.mutation.ClearSettledByAdminID()
	return _u
}

// SetSettledNote sets the "settled_note" field.
func (_u *ReferralCommissionUpdateOne) SetSettledNote(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetSettledNote(v)
	return _u
}

// SetNillableSettledNote sets the "settled_note" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableSettledNote(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetSettledNote(*v)
	}
	return _u
}

// ClearSettledNote clears the value of the "settled_note" field.
func (_u *ReferralCommissionUpdateOne) ClearSettledNote() *ReferralCommissionUpdateOne {
	_u.mutation.ClearSettledNote()
	return _u
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdateOne) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdateOne) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralCommissionUpdateOne) Select(field string, fields ...string) *ReferralCommissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralCommission entity.
func (_u *ReferralCommissionUpdateOne) Save(ctx context.Context) (*ReferralCommission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) SaveX(ctx context.Context) *ReferralCommission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralCommissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdateOne) check() error {
	if v, ok := _u.mutation.SourceRequestID(); ok {
		if err := referralcommission.SourceRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "source_request_id", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.source_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralCommissionUpdateOne) sqlSave(ctx context.Context) (_node *ReferralCommission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralCommission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommission.FieldID)
		for _, f := range fields {
			if !referralcommission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralcommission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DownlineID(); ok {
		_spec.SetField(referralcommission.FieldDownlineID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownlineID(); ok {
		_spec.AddField(referralcommission.FieldDownlineID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(referralcommission.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedTier(); ok {
		_spec.AddField(referralcommission.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.SourceRequestID(); ok {
		_spec.SetField(referralcommission.FieldSourceRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseAmount(); ok {
		_spec.SetField(referralcommission.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseAmount(); ok {
		_spec.AddField(referralcommission.FieldBaseAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(referralcommission.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(referralcommission.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionAmount(); ok {
		_spec.AddField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(referralcommission.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(referralcommission.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledByAdminID(); ok {
		_spec.SetField(referralcommission.FieldSettledByAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettledByAdminID(); ok {
		_spec.AddField(referralcommission.FieldSettledByAdminID, field.TypeInt64, value)
	}
	if _u.mutation.SettledByAdminIDCleared() {
		_spec.ClearField(referralcommission.FieldSettledByAdminID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SettledNote(); ok {
		_spec.SetField(referralcommission.FieldSettledNote, field.TypeString, value)
	}
	if _u.mutation.SettledNoteCleared() {
		_spec.ClearField(referralcommission.FieldSettledNote, field.TypeString)
	}
	_node = &ReferralCommission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
