// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
)

// ReferralCommission is the model entity for the ReferralCommission schema.
type ReferralCommission struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 拿到抽佣的用户
	InviterID int64 `json:"inviter_id,omitempty"`
	// 贡献本次消费的下线用户
	DownlineID int64 `json:"downline_id,omitempty"`
	// 分销层级：1=直接下线，2=下线的下线（first_recharge 也用 tier=1）
	Tier int8 `json:"tier,omitempty"`
	// 抽佣种类：first_recharge=普通邀请首充返点（封顶），agent_lv1/lv2=代理一/二级（长期）
	Kind string `json:"kind,omitempty"`
	// 来源 usage_log 的 RequestID（去重键）
	SourceRequestID string `json:"source_request_id,omitempty"`
	// 下线本次消费金额（快照）
	BaseAmount float64 `json:"base_amount,omitempty"`
	// 当时生效的费率（快照）
	Rate float64 `json:"rate,omitempty"`
	// base_amount × rate
	CommissionAmount float64 `json:"commission_amount,omitempty"`
	// pending / settled / voided
	Status string `json:"status,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// SettledByAdminID holds the value of the "settled_by_admin_id" field.
	SettledByAdminID *int64 `json:"settled_by_admin_id,omitempty"`
	// SettledNote holds the value of the "settled_note" field.
	SettledNote *string `json:"settled_note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralCommission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldBaseAmount, referralcommission.FieldRate, referralcommission.FieldCommissionAmount:
			values[i] = new(sql.NullFloat64)
		case referralcommission.FieldID, referralcommission.FieldInviterID, referralcommission.FieldDownlineID, referralcommission.FieldTier, referralcommission.FieldSettledByAdminID:
			values[i] = new(sql.NullInt64)
		case referralcommission.FieldKind, referralcommission.FieldSourceRequestID, referralcommission.FieldStatus, referralcommission.FieldSettledNote:
			values[i] = new(sql.NullString)
		case referralcommission.FieldSettledAt, referralcommission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralCommission fields.
func (_m *ReferralCommission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralcommission.FieldInviterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value.Valid {
				_m.InviterID = value.Int64
			}
		case referralcommission.FieldDownlineID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field downline_id", values[i])
			} else if value.Valid {
				_m.DownlineID = value.Int64
			}
		case referralcommission.FieldTier:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				_m.Tier = int8(value.Int64)
			}
		case referralcommission.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case referralcommission.FieldSourceRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_request_id", values[i])
			} else if value.Valid {
				_m.SourceRequestID = value.String
			}
		case referralcommission.FieldBaseAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_amount", values[i])
			} else if value.Valid {
				_m.BaseAmount = value.Float64
			}
		case referralcommission.FieldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = value.Float64
			}
		case referralcommission.FieldCommissionAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_amount", values[i])
			} else if value.Valid {
				_m.CommissionAmount = value.Float64
			}
		case referralcommission.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case referralcommission.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case referralcommission.FieldSettledByAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settled_by_admin_id", values[i])
			} else if value.Valid {
				_m.SettledByAdminID = new(int64)
				*_m.SettledByAdminID = value.Int64
			}
		case referralcommission.FieldSettledNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field settled_note", values[i])
			} else if value.Valid {
				_m.SettledNote = new(string)
				*_m.SettledNote = value.String
			}
		case referralcommission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralCommission.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralCommission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReferralCommission.
// Note that you need to call ReferralCommission.Unwrap() before calling this method if this ReferralCommission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralCommission) Update() *ReferralCommissionUpdateOne {
	return NewReferralCommissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralCommission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralCommission) Unwrap() *ReferralCommission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralCommission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralCommission) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralCommission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterID))
	builder.WriteString(", ")
	builder.WriteString("downline_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DownlineID))
	builder.WriteString(", ")
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tier))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("source_request_id=")
	builder.WriteString(_m.SourceRequestID)
	builder.WriteString(", ")
	builder.WriteString("base_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseAmount))
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rate))
	builder.WriteString(", ")
	builder.WriteString("commission_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommissionAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SettledByAdminID; v != nil {
		builder.WriteString("settled_by_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SettledNote; v != nil {
		builder.WriteString("settled_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralCommissions is a parsable slice of ReferralCommission.
type ReferralCommissions []*ReferralCommission
