// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referralcommissionrule"
)

// ReferralCommissionRuleCreate is the builder for creating a ReferralCommissionRule entity.
type ReferralCommissionRuleCreate struct {
	config
	mutation *ReferralCommissionRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTier sets the "tier" field.
func (_c *ReferralCommissionRuleCreate) SetTier(v int8) *ReferralCommissionRuleCreate {
	_c.mutation.SetTier(v)
	return _c
}

// SetRate sets the "rate" field.
func (_c *ReferralCommissionRuleCreate) SetRate(v float64) *ReferralCommissionRuleCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_c *ReferralCommissionRuleCreate) SetNillableRate(v *float64) *ReferralCommissionRuleCreate {
	if v != nil {
		_c.SetRate(*v)
	}
	return _c
}

// SetEffectiveFrom sets the "effective_from" field.
func (_c *ReferralCommissionRuleCreate) SetEffectiveFrom(v time.Time) *ReferralCommissionRuleCreate {
	_c.mutation.SetEffectiveFrom(v)
	return _c
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_c *ReferralCommissionRuleCreate) SetNillableEffectiveFrom(v *time.Time) *ReferralCommissionRuleCreate {
	if v != nil {
		_c.SetEffectiveFrom(*v)
	}
	return _c
}

// SetEffectiveUntil sets the "effective_until" field.
func (_c *ReferralCommissionRuleCreate) SetEffectiveUntil(v time.Time) *ReferralCommissionRuleCreate {
	_c.mutation.SetEffectiveUntil(v)
	return _c
}

// SetNillableEffectiveUntil sets the "effective_until" field if the given value is not nil.
func (_c *ReferralCommissionRuleCreate) SetNillableEffectiveUntil(v *time.Time) *ReferralCommissionRuleCreate {
	if v != nil {
		_c.SetEffectiveUntil(*v)
	}
	return _c
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (_c *ReferralCommissionRuleCreate) SetCreatedByAdminID(v int64) *ReferralCommissionRuleCreate {
	_c.mutation.SetCreatedByAdminID(v)
	return _c
}

// SetNillableCreatedByAdminID sets the "created_by_admin_id" field if the given value is not nil.
func (_c *ReferralCommissionRuleCreate) SetNillableCreatedByAdminID(v *int64) *ReferralCommissionRuleCreate {
	if v != nil {
		_c.SetCreatedByAdminID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralCommissionRuleCreate) SetCreatedAt(v time.Time) *ReferralCommissionRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralCommissionRuleCreate) SetNillableCreatedAt(v *time.Time) *ReferralCommissionRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ReferralCommissionRuleMutation object of the builder.
func (_c *ReferralCommissionRuleCreate) Mutation() *ReferralCommissionRuleMutation {
	return _c.mutation
}

// Save creates the ReferralCommissionRule in the database.
func (_c *ReferralCommissionRuleCreate) Save(ctx context.Context) (*ReferralCommissionRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralCommissionRuleCreate) SaveX(ctx context.Context) *ReferralCommissionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralCommissionRuleCreate) defaults() {
	if _, ok := _c.mutation.Rate(); !ok {
		v := referralcommissionrule.DefaultRate
		_c.mutation.SetRate(v)
	}
	if _, ok := _c.mutation.EffectiveFrom(); !ok {
		v := referralcommissionrule.DefaultEffectiveFrom()
		_c.mutation.SetEffectiveFrom(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralcommissionrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralCommissionRuleCreate) check() error {
	if _, ok := _c.mutation.Tier(); !ok {
		return &ValidationError{Name: "tier", err: errors.New(`ent: missing required field "ReferralCommissionRule.tier"`)}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "ReferralCommissionRule.rate"`)}
	}
	if _, ok := _c.mutation.EffectiveFrom(); !ok {
		return &ValidationError{Name: "effective_from", err: errors.New(`ent: missing required field "ReferralCommissionRule.effective_from"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralCommissionRule.created_at"`)}
	}
	return nil
}

func (_c *ReferralCommissionRuleCreate) sqlSave(ctx context.Context) (*ReferralCommissionRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralCommissionRuleCreate) createSpec() (*ReferralCommissionRule, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralCommissionRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralcommissionrule.Table, sqlgraph.NewFieldSpec(referralcommissionrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Tier(); ok {
		_spec.SetField(referralcommissionrule.FieldTier, field.TypeInt8, value)
		_node.Tier = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(referralcommissionrule.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.EffectiveFrom(); ok {
		_spec.SetField(referralcommissionrule.FieldEffectiveFrom, field.TypeTime, value)
		_node.EffectiveFrom = value
	}
	if value, ok := _c.mutation.EffectiveUntil(); ok {
		_spec.SetField(referralcommissionrule.FieldEffectiveUntil, field.TypeTime, value)
		_node.EffectiveUntil = &value
	}
	if value, ok := _c.mutation.CreatedByAdminID(); ok {
		_spec.SetField(referralcommissionrule.FieldCreatedByAdminID, field.TypeInt64, value)
		_node.CreatedByAdminID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralcommissionrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommissionRule.Create().
//		SetTier(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionRuleUpsert) {
//			SetTier(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionRuleCreate) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionRuleUpsertOne {
	_c.conflict = opts
	return &ReferralCommissionRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommissionRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionRuleCreate) OnConflictColumns(columns ...string) *ReferralCommissionRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionRuleUpsertOne{
		create: _c,
	}
}

type (
	// ReferralCommissionRuleUpsertOne is the builder for "upsert"-ing
	//  one ReferralCommissionRule node.
	ReferralCommissionRuleUpsertOne struct {
		create *ReferralCommissionRuleCreate
	}

	// ReferralCommissionRuleUpsert is the "OnConflict" setter.
	ReferralCommissionRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetTier sets the "tier" field.
func (u *ReferralCommissionRuleUpsert) SetTier(v int8) *ReferralCommissionRuleUpsert {
	u.Set(referralcommissionrule.FieldTier, v)
	return u
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsert) UpdateTier() *ReferralCommissionRuleUpsert {
	u.SetExcluded(referralcommissionrule.FieldTier)
	return u
}

// AddTier adds v to the "tier" field.
func (u *ReferralCommissionRuleUpsert) AddTier(v int8) *ReferralCommissionRuleUpsert {
	u.Add(referralcommissionrule.FieldTier, v)
	return u
}

// SetRate sets the "rate" field.
func (u *ReferralCommissionRuleUpsert) SetRate(v float64) *ReferralCommissionRuleUpsert {
	u.Set(referralcommissionrule.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsert) UpdateRate() *ReferralCommissionRuleUpsert {
	u.SetExcluded(referralcommissionrule.FieldRate)
	return u
}

// AddRate adds v to the "rate" field.
func (u *ReferralCommissionRuleUpsert) AddRate(v float64) *ReferralCommissionRuleUpsert {
	u.Add(referralcommissionrule.FieldRate, v)
	return u
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *ReferralCommissionRuleUpsert) SetEffectiveFrom(v time.Time) *ReferralCommissionRuleUpsert {
	u.Set(referralcommissionrule.FieldEffectiveFrom, v)
	return u
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsert) UpdateEffectiveFrom() *ReferralCommissionRuleUpsert {
	u.SetExcluded(referralcommissionrule.FieldEffectiveFrom)
	return u
}

// SetEffectiveUntil sets the "effective_until" field.
func (u *ReferralCommissionRuleUpsert) SetEffectiveUntil(v time.Time) *ReferralCommissionRuleUpsert {
	u.Set(referralcommissionrule.FieldEffectiveUntil, v)
	return u
}

// UpdateEffectiveUntil sets the "effective_until" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsert) UpdateEffectiveUntil() *ReferralCommissionRuleUpsert {
	u.SetExcluded(referralcommissionrule.FieldEffectiveUntil)
	return u
}

// ClearEffectiveUntil clears the value of the "effective_until" field.
func (u *ReferralCommissionRuleUpsert) ClearEffectiveUntil() *ReferralCommissionRuleUpsert {
	u.SetNull(referralcommissionrule.FieldEffectiveUntil)
	return u
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsert) SetCreatedByAdminID(v int64) *ReferralCommissionRuleUpsert {
	u.Set(referralcommissionrule.FieldCreatedByAdminID, v)
	return u
}

// UpdateCreatedByAdminID sets the "created_by_admin_id" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsert) UpdateCreatedByAdminID() *ReferralCommissionRuleUpsert {
	u.SetExcluded(referralcommissionrule.FieldCreatedByAdminID)
	return u
}

// AddCreatedByAdminID adds v to the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsert) AddCreatedByAdminID(v int64) *ReferralCommissionRuleUpsert {
	u.Add(referralcommissionrule.FieldCreatedByAdminID, v)
	return u
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsert) ClearCreatedByAdminID() *ReferralCommissionRuleUpsert {
	u.SetNull(referralcommissionrule.FieldCreatedByAdminID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralCommissionRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionRuleUpsertOne) UpdateNewValues() *ReferralCommissionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralcommissionrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommissionRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralCommissionRuleUpsertOne) Ignore() *ReferralCommissionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionRuleUpsertOne) DoNothing() *ReferralCommissionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionRuleCreate.OnConflict
// documentation for more info.
func (u *ReferralCommissionRuleUpsertOne) Update(set func(*ReferralCommissionRuleUpsert)) *ReferralCommissionRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTier sets the "tier" field.
func (u *ReferralCommissionRuleUpsertOne) SetTier(v int8) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetTier(v)
	})
}

// AddTier adds v to the "tier" field.
func (u *ReferralCommissionRuleUpsertOne) AddTier(v int8) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.AddTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertOne) UpdateTier() *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateTier()
	})
}

// SetRate sets the "rate" field.
func (u *ReferralCommissionRuleUpsertOne) SetRate(v float64) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *ReferralCommissionRuleUpsertOne) AddRate(v float64) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertOne) UpdateRate() *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateRate()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *ReferralCommissionRuleUpsertOne) SetEffectiveFrom(v time.Time) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertOne) UpdateEffectiveFrom() *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// SetEffectiveUntil sets the "effective_until" field.
func (u *ReferralCommissionRuleUpsertOne) SetEffectiveUntil(v time.Time) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetEffectiveUntil(v)
	})
}

// UpdateEffectiveUntil sets the "effective_until" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertOne) UpdateEffectiveUntil() *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateEffectiveUntil()
	})
}

// ClearEffectiveUntil clears the value of the "effective_until" field.
func (u *ReferralCommissionRuleUpsertOne) ClearEffectiveUntil() *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.ClearEffectiveUntil()
	})
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsertOne) SetCreatedByAdminID(v int64) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetCreatedByAdminID(v)
	})
}

// AddCreatedByAdminID adds v to the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsertOne) AddCreatedByAdminID(v int64) *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.AddCreatedByAdminID(v)
	})
}

// UpdateCreatedByAdminID sets the "created_by_admin_id" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertOne) UpdateCreatedByAdminID() *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateCreatedByAdminID()
	})
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsertOne) ClearCreatedByAdminID() *ReferralCommissionRuleUpsertOne {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.ClearCreatedByAdminID()
	})
}

// Exec executes the query.
func (u *ReferralCommissionRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralCommissionRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralCommissionRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralCommissionRuleCreateBulk is the builder for creating many ReferralCommissionRule entities in bulk.
type ReferralCommissionRuleCreateBulk struct {
	config
	err      error
	builders []*ReferralCommissionRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralCommissionRule entities in the database.
func (_c *ReferralCommissionRuleCreateBulk) Save(ctx context.Context) ([]*ReferralCommissionRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralCommissionRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralCommissionRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralCommissionRuleCreateBulk) SaveX(ctx context.Context) []*ReferralCommissionRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommissionRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionRuleUpsert) {
//			SetTier(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionRuleUpsertBulk {
	_c.conflict = opts
	return &ReferralCommissionRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommissionRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionRuleCreateBulk) OnConflictColumns(columns ...string) *ReferralCommissionRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionRuleUpsertBulk{
		create: _c,
	}
}

// ReferralCommissionRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralCommissionRule nodes.
type ReferralCommissionRuleUpsertBulk struct {
	create *ReferralCommissionRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralCommissionRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionRuleUpsertBulk) UpdateNewValues() *ReferralCommissionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralcommissionrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommissionRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralCommissionRuleUpsertBulk) Ignore() *ReferralCommissionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionRuleUpsertBulk) DoNothing() *ReferralCommissionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionRuleCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralCommissionRuleUpsertBulk) Update(set func(*ReferralCommissionRuleUpsert)) *ReferralCommissionRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetTier sets the "tier" field.
func (u *ReferralCommissionRuleUpsertBulk) SetTier(v int8) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetTier(v)
	})
}

// AddTier adds v to the "tier" field.
func (u *ReferralCommissionRuleUpsertBulk) AddTier(v int8) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.AddTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertBulk) UpdateTier() *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateTier()
	})
}

// SetRate sets the "rate" field.
func (u *ReferralCommissionRuleUpsertBulk) SetRate(v float64) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *ReferralCommissionRuleUpsertBulk) AddRate(v float64) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertBulk) UpdateRate() *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateRate()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *ReferralCommissionRuleUpsertBulk) SetEffectiveFrom(v time.Time) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertBulk) UpdateEffectiveFrom() *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// SetEffectiveUntil sets the "effective_until" field.
func (u *ReferralCommissionRuleUpsertBulk) SetEffectiveUntil(v time.Time) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetEffectiveUntil(v)
	})
}

// UpdateEffectiveUntil sets the "effective_until" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertBulk) UpdateEffectiveUntil() *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateEffectiveUntil()
	})
}

// ClearEffectiveUntil clears the value of the "effective_until" field.
func (u *ReferralCommissionRuleUpsertBulk) ClearEffectiveUntil() *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.ClearEffectiveUntil()
	})
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsertBulk) SetCreatedByAdminID(v int64) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.SetCreatedByAdminID(v)
	})
}

// AddCreatedByAdminID adds v to the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsertBulk) AddCreatedByAdminID(v int64) *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.AddCreatedByAdminID(v)
	})
}

// UpdateCreatedByAdminID sets the "created_by_admin_id" field to the value that was provided on create.
func (u *ReferralCommissionRuleUpsertBulk) UpdateCreatedByAdminID() *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.UpdateCreatedByAdminID()
	})
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (u *ReferralCommissionRuleUpsertBulk) ClearCreatedByAdminID() *ReferralCommissionRuleUpsertBulk {
	return u.Update(func(s *ReferralCommissionRuleUpsert) {
		s.ClearCreatedByAdminID()
	})
}

// Exec executes the query.
func (u *ReferralCommissionRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralCommissionRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
