// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralcommissionrule"
)

// ReferralCommissionRule is the model entity for the ReferralCommissionRule schema.
type ReferralCommissionRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 分销层级：1=直接下线，2=下线的下线
	Tier int8 `json:"tier,omitempty"`
	// 抽佣比例，0.0500 = 5%
	Rate float64 `json:"rate,omitempty"`
	// EffectiveFrom holds the value of the "effective_from" field.
	EffectiveFrom time.Time `json:"effective_from,omitempty"`
	// NULL 表示当前生效中
	EffectiveUntil *time.Time `json:"effective_until,omitempty"`
	// 修改/创建该规则的管理员
	CreatedByAdminID *int64 `json:"created_by_admin_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralCommissionRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralcommissionrule.FieldRate:
			values[i] = new(sql.NullFloat64)
		case referralcommissionrule.FieldID, referralcommissionrule.FieldTier, referralcommissionrule.FieldCreatedByAdminID:
			values[i] = new(sql.NullInt64)
		case referralcommissionrule.FieldEffectiveFrom, referralcommissionrule.FieldEffectiveUntil, referralcommissionrule.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralCommissionRule fields.
func (_m *ReferralCommissionRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralcommissionrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralcommissionrule.FieldTier:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				_m.Tier = int8(value.Int64)
			}
		case referralcommissionrule.FieldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = value.Float64
			}
		case referralcommissionrule.FieldEffectiveFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_from", values[i])
			} else if value.Valid {
				_m.EffectiveFrom = value.Time
			}
		case referralcommissionrule.FieldEffectiveUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_until", values[i])
			} else if value.Valid {
				_m.EffectiveUntil = new(time.Time)
				*_m.EffectiveUntil = value.Time
			}
		case referralcommissionrule.FieldCreatedByAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_admin_id", values[i])
			} else if value.Valid {
				_m.CreatedByAdminID = new(int64)
				*_m.CreatedByAdminID = value.Int64
			}
		case referralcommissionrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralCommissionRule.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralCommissionRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReferralCommissionRule.
// Note that you need to call ReferralCommissionRule.Unwrap() before calling this method if this ReferralCommissionRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralCommissionRule) Update() *ReferralCommissionRuleUpdateOne {
	return NewReferralCommissionRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralCommissionRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralCommissionRule) Unwrap() *ReferralCommissionRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralCommissionRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralCommissionRule) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralCommissionRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tier))
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rate))
	builder.WriteString(", ")
	builder.WriteString("effective_from=")
	builder.WriteString(_m.EffectiveFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EffectiveUntil; v != nil {
		builder.WriteString("effective_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedByAdminID; v != nil {
		builder.WriteString("created_by_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralCommissionRules is a parsable slice of ReferralCommissionRule.
type ReferralCommissionRules []*ReferralCommissionRule
