// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralcommissionrule"
)

// ReferralCommissionRuleUpdate is the builder for updating ReferralCommissionRule entities.
type ReferralCommissionRuleUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralCommissionRuleMutation
}

// Where appends a list predicates to the ReferralCommissionRuleUpdate builder.
func (_u *ReferralCommissionRuleUpdate) Where(ps ...predicate.ReferralCommissionRule) *ReferralCommissionRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTier sets the "tier" field.
func (_u *ReferralCommissionRuleUpdate) SetTier(v int8) *ReferralCommissionRuleUpdate {
	_u.mutation.ResetTier()
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdate) SetNillableTier(v *int8) *ReferralCommissionRuleUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// AddTier adds value to the "tier" field.
func (_u *ReferralCommissionRuleUpdate) AddTier(v int8) *ReferralCommissionRuleUpdate {
	_u.mutation.AddTier(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *ReferralCommissionRuleUpdate) SetRate(v float64) *ReferralCommissionRuleUpdate {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdate) SetNillableRate(v *float64) *ReferralCommissionRuleUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *ReferralCommissionRuleUpdate) AddRate(v float64) *ReferralCommissionRuleUpdate {
	_u.mutation.AddRate(v)
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *ReferralCommissionRuleUpdate) SetEffectiveFrom(v time.Time) *ReferralCommissionRuleUpdate {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdate) SetNillableEffectiveFrom(v *time.Time) *ReferralCommissionRuleUpdate {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetEffectiveUntil sets the "effective_until" field.
func (_u *ReferralCommissionRuleUpdate) SetEffectiveUntil(v time.Time) *ReferralCommissionRuleUpdate {
	_u.mutation.SetEffectiveUntil(v)
	return _u
}

// SetNillableEffectiveUntil sets the "effective_until" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdate) SetNillableEffectiveUntil(v *time.Time) *ReferralCommissionRuleUpdate {
	if v != nil {
		_u.SetEffectiveUntil(*v)
	}
	return _u
}

// ClearEffectiveUntil clears the value of the "effective_until" field.
func (_u *ReferralCommissionRuleUpdate) ClearEffectiveUntil() *ReferralCommissionRuleUpdate {
	_u.mutation.ClearEffectiveUntil()
	return _u
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (_u *ReferralCommissionRuleUpdate) SetCreatedByAdminID(v int64) *ReferralCommissionRuleUpdate {
	_u.mutation.ResetCreatedByAdminID()
	_u.mutation.SetCreatedByAdminID(v)
	return _u
}

// SetNillableCreatedByAdminID sets the "created_by_admin_id" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdate) SetNillableCreatedByAdminID(v *int64) *ReferralCommissionRuleUpdate {
	if v != nil {
		_u.SetCreatedByAdminID(*v)
	}
	return _u
}

// AddCreatedByAdminID adds value to the "created_by_admin_id" field.
func (_u *ReferralCommissionRuleUpdate) AddCreatedByAdminID(v int64) *ReferralCommissionRuleUpdate {
	_u.mutation.AddCreatedByAdminID(v)
	return _u
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (_u *ReferralCommissionRuleUpdate) ClearCreatedByAdminID() *ReferralCommissionRuleUpdate {
	_u.mutation.ClearCreatedByAdminID()
	return _u
}

// Mutation returns the ReferralCommissionRuleMutation object of the builder.
func (_u *ReferralCommissionRuleUpdate) Mutation() *ReferralCommissionRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralCommissionRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralCommissionRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReferralCommissionRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(referralcommissionrule.Table, referralcommissionrule.Columns, sqlgraph.NewFieldSpec(referralcommissionrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(referralcommissionrule.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedTier(); ok {
		_spec.AddField(referralcommissionrule.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(referralcommissionrule.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(referralcommissionrule.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(referralcommissionrule.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EffectiveUntil(); ok {
		_spec.SetField(referralcommissionrule.FieldEffectiveUntil, field.TypeTime, value)
	}
	if _u.mutation.EffectiveUntilCleared() {
		_spec.ClearField(referralcommissionrule.FieldEffectiveUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedByAdminID(); ok {
		_spec.SetField(referralcommissionrule.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByAdminID(); ok {
		_spec.AddField(referralcommissionrule.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByAdminIDCleared() {
		_spec.ClearField(referralcommissionrule.FieldCreatedByAdminID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommissionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralCommissionRuleUpdateOne is the builder for updating a single ReferralCommissionRule entity.
type ReferralCommissionRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralCommissionRuleMutation
}

// SetTier sets the "tier" field.
func (_u *ReferralCommissionRuleUpdateOne) SetTier(v int8) *ReferralCommissionRuleUpdateOne {
	_u.mutation.ResetTier()
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdateOne) SetNillableTier(v *int8) *ReferralCommissionRuleUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// AddTier adds value to the "tier" field.
func (_u *ReferralCommissionRuleUpdateOne) AddTier(v int8) *ReferralCommissionRuleUpdateOne {
	_u.mutation.AddTier(v)
	return _u
}

// SetRate sets the "rate" field.
func (_u *ReferralCommissionRuleUpdateOne) SetRate(v float64) *ReferralCommissionRuleUpdateOne {
	_u.mutation.ResetRate()
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdateOne) SetNillableRate(v *float64) *ReferralCommissionRuleUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// AddRate adds value to the "rate" field.
func (_u *ReferralCommissionRuleUpdateOne) AddRate(v float64) *ReferralCommissionRuleUpdateOne {
	_u.mutation.AddRate(v)
	return _u
}

// SetEffectiveFrom sets the "effective_from" field.
func (_u *ReferralCommissionRuleUpdateOne) SetEffectiveFrom(v time.Time) *ReferralCommissionRuleUpdateOne {
	_u.mutation.SetEffectiveFrom(v)
	return _u
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdateOne) SetNillableEffectiveFrom(v *time.Time) *ReferralCommissionRuleUpdateOne {
	if v != nil {
		_u.SetEffectiveFrom(*v)
	}
	return _u
}

// SetEffectiveUntil sets the "effective_until" field.
func (_u *ReferralCommissionRuleUpdateOne) SetEffectiveUntil(v time.Time) *ReferralCommissionRuleUpdateOne {
	_u.mutation.SetEffectiveUntil(v)
	return _u
}

// SetNillableEffectiveUntil sets the "effective_until" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdateOne) SetNillableEffectiveUntil(v *time.Time) *ReferralCommissionRuleUpdateOne {
	if v != nil {
		_u.SetEffectiveUntil(*v)
	}
	return _u
}

// ClearEffectiveUntil clears the value of the "effective_until" field.
func (_u *ReferralCommissionRuleUpdateOne) ClearEffectiveUntil() *ReferralCommissionRuleUpdateOne {
	_u.mutation.ClearEffectiveUntil()
	return _u
}

// SetCreatedByAdminID sets the "created_by_admin_id" field.
func (_u *ReferralCommissionRuleUpdateOne) SetCreatedByAdminID(v int64) *ReferralCommissionRuleUpdateOne {
	_u.mutation.ResetCreatedByAdminID()
	_u.mutation.SetCreatedByAdminID(v)
	return _u
}

// SetNillableCreatedByAdminID sets the "created_by_admin_id" field if the given value is not nil.
func (_u *ReferralCommissionRuleUpdateOne) SetNillableCreatedByAdminID(v *int64) *ReferralCommissionRuleUpdateOne {
	if v != nil {
		_u.SetCreatedByAdminID(*v)
	}
	return _u
}

// AddCreatedByAdminID adds value to the "created_by_admin_id" field.
func (_u *ReferralCommissionRuleUpdateOne) AddCreatedByAdminID(v int64) *ReferralCommissionRuleUpdateOne {
	_u.mutation.AddCreatedByAdminID(v)
	return _u
}

// ClearCreatedByAdminID clears the value of the "created_by_admin_id" field.
func (_u *ReferralCommissionRuleUpdateOne) ClearCreatedByAdminID() *ReferralCommissionRuleUpdateOne {
	_u.mutation.ClearCreatedByAdminID()
	return _u
}

// Mutation returns the ReferralCommissionRuleMutation object of the builder.
func (_u *ReferralCommissionRuleUpdateOne) Mutation() *ReferralCommissionRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReferralCommissionRuleUpdate builder.
func (_u *ReferralCommissionRuleUpdateOne) Where(ps ...predicate.ReferralCommissionRule) *ReferralCommissionRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralCommissionRuleUpdateOne) Select(field string, fields ...string) *ReferralCommissionRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralCommissionRule entity.
func (_u *ReferralCommissionRuleUpdateOne) Save(ctx context.Context) (*ReferralCommissionRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionRuleUpdateOne) SaveX(ctx context.Context) *ReferralCommissionRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralCommissionRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReferralCommissionRuleUpdateOne) sqlSave(ctx context.Context) (_node *ReferralCommissionRule, err error) {
	_spec := sqlgraph.NewUpdateSpec(referralcommissionrule.Table, referralcommissionrule.Columns, sqlgraph.NewFieldSpec(referralcommissionrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralCommissionRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommissionrule.FieldID)
		for _, f := range fields {
			if !referralcommissionrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralcommissionrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(referralcommissionrule.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedTier(); ok {
		_spec.AddField(referralcommissionrule.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(referralcommissionrule.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRate(); ok {
		_spec.AddField(referralcommissionrule.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EffectiveFrom(); ok {
		_spec.SetField(referralcommissionrule.FieldEffectiveFrom, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EffectiveUntil(); ok {
		_spec.SetField(referralcommissionrule.FieldEffectiveUntil, field.TypeTime, value)
	}
	if _u.mutation.EffectiveUntilCleared() {
		_spec.ClearField(referralcommissionrule.FieldEffectiveUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedByAdminID(); ok {
		_spec.SetField(referralcommissionrule.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedByAdminID(); ok {
		_spec.AddField(referralcommissionrule.FieldCreatedByAdminID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByAdminIDCleared() {
		_spec.ClearField(referralcommissionrule.FieldCreatedByAdminID, field.TypeInt64)
	}
	_node = &ReferralCommissionRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommissionrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
