// Code generated by ent, DO NOT EDIT.

package referralcommissionrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the referralcommissionrule type in the database.
	Label = "referral_commission_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTier holds the string denoting the tier field in the database.
	FieldTier = "tier"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldEffectiveFrom holds the string denoting the effective_from field in the database.
	FieldEffectiveFrom = "effective_from"
	// FieldEffectiveUntil holds the string denoting the effective_until field in the database.
	FieldEffectiveUntil = "effective_until"
	// FieldCreatedByAdminID holds the string denoting the created_by_admin_id field in the database.
	FieldCreatedByAdminID = "created_by_admin_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the referralcommissionrule in the database.
	Table = "referral_commission_rules"
)

// Columns holds all SQL columns for referralcommissionrule fields.
var Columns = []string{
	FieldID,
	FieldTier,
	FieldRate,
	FieldEffectiveFrom,
	FieldEffectiveUntil,
	FieldCreatedByAdminID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRate holds the default value on creation for the "rate" field.
	DefaultRate float64
	// DefaultEffectiveFrom holds the default value on creation for the "effective_from" field.
	DefaultEffectiveFrom func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralCommissionRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTier orders the results by the tier field.
func ByTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTier, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByEffectiveFrom orders the results by the effective_from field.
func ByEffectiveFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveFrom, opts...).ToFunc()
}

// ByEffectiveUntil orders the results by the effective_until field.
func ByEffectiveUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveUntil, opts...).ToFunc()
}

// ByCreatedByAdminID orders the results by the created_by_admin_id field.
func ByCreatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAdminID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
