// Code generated by ent, DO NOT EDIT.

package referralcommissionrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLTE(FieldID, id))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldTier, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldRate, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveUntil applies equality check predicate on the "effective_until" field. It's identical to EffectiveUntilEQ.
func EffectiveUntil(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldEffectiveUntil, v))
}

// CreatedByAdminID applies equality check predicate on the "created_by_admin_id" field. It's identical to CreatedByAdminIDEQ.
func CreatedByAdminID(v int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldCreatedAt, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v int8) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLTE(FieldTier, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v float64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLTE(FieldRate, v))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLTE(FieldEffectiveFrom, v))
}

// EffectiveUntilEQ applies the EQ predicate on the "effective_until" field.
func EffectiveUntilEQ(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldEffectiveUntil, v))
}

// EffectiveUntilNEQ applies the NEQ predicate on the "effective_until" field.
func EffectiveUntilNEQ(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNEQ(FieldEffectiveUntil, v))
}

// EffectiveUntilIn applies the In predicate on the "effective_until" field.
func EffectiveUntilIn(vs ...time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIn(FieldEffectiveUntil, vs...))
}

// EffectiveUntilNotIn applies the NotIn predicate on the "effective_until" field.
func EffectiveUntilNotIn(vs ...time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotIn(FieldEffectiveUntil, vs...))
}

// EffectiveUntilGT applies the GT predicate on the "effective_until" field.
func EffectiveUntilGT(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGT(FieldEffectiveUntil, v))
}

// EffectiveUntilGTE applies the GTE predicate on the "effective_until" field.
func EffectiveUntilGTE(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGTE(FieldEffectiveUntil, v))
}

// EffectiveUntilLT applies the LT predicate on the "effective_until" field.
func EffectiveUntilLT(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLT(FieldEffectiveUntil, v))
}

// EffectiveUntilLTE applies the LTE predicate on the "effective_until" field.
func EffectiveUntilLTE(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLTE(FieldEffectiveUntil, v))
}

// EffectiveUntilIsNil applies the IsNil predicate on the "effective_until" field.
func EffectiveUntilIsNil() predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIsNull(FieldEffectiveUntil))
}

// EffectiveUntilNotNil applies the NotNil predicate on the "effective_until" field.
func EffectiveUntilNotNil() predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotNull(FieldEffectiveUntil))
}

// CreatedByAdminIDEQ applies the EQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDEQ(v int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDNEQ applies the NEQ predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNEQ(v int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNEQ(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIn applies the In predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIn(vs ...int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDNotIn applies the NotIn predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotIn(vs ...int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotIn(FieldCreatedByAdminID, vs...))
}

// CreatedByAdminIDGT applies the GT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGT(v int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDGTE applies the GTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDGTE(v int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLT applies the LT predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLT(v int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLT(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDLTE applies the LTE predicate on the "created_by_admin_id" field.
func CreatedByAdminIDLTE(v int64) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLTE(FieldCreatedByAdminID, v))
}

// CreatedByAdminIDIsNil applies the IsNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDIsNil() predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIsNull(FieldCreatedByAdminID))
}

// CreatedByAdminIDNotNil applies the NotNil predicate on the "created_by_admin_id" field.
func CreatedByAdminIDNotNil() predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotNull(FieldCreatedByAdminID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralCommissionRule) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralCommissionRule) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralCommissionRule) predicate.ReferralCommissionRule {
	return predicate.ReferralCommissionRule(sql.NotPredicates(p))
}
