// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the referralcommission type in the database.
	Label = "referral_commission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviterID holds the string denoting the inviter_id field in the database.
	FieldInviterID = "inviter_id"
	// FieldDownlineID holds the string denoting the downline_id field in the database.
	FieldDownlineID = "downline_id"
	// FieldTier holds the string denoting the tier field in the database.
	FieldTier = "tier"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldSourceRequestID holds the string denoting the source_request_id field in the database.
	FieldSourceRequestID = "source_request_id"
	// FieldBaseAmount holds the string denoting the base_amount field in the database.
	FieldBaseAmount = "base_amount"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldCommissionAmount holds the string denoting the commission_amount field in the database.
	FieldCommissionAmount = "commission_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldSettledByAdminID holds the string denoting the settled_by_admin_id field in the database.
	FieldSettledByAdminID = "settled_by_admin_id"
	// FieldSettledNote holds the string denoting the settled_note field in the database.
	FieldSettledNote = "settled_note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the referralcommission in the database.
	Table = "referral_commissions"
)

// Columns holds all SQL columns for referralcommission fields.
var Columns = []string{
	FieldID,
	FieldInviterID,
	FieldDownlineID,
	FieldTier,
	FieldKind,
	FieldSourceRequestID,
	FieldBaseAmount,
	FieldRate,
	FieldCommissionAmount,
	FieldStatus,
	FieldSettledAt,
	FieldSettledByAdminID,
	FieldSettledNote,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultKind holds the default value on creation for the "kind" field.
	DefaultKind string
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// SourceRequestIDValidator is a validator for the "source_request_id" field. It is called by the builders before save.
	SourceRequestIDValidator func(string) error
	// DefaultBaseAmount holds the default value on creation for the "base_amount" field.
	DefaultBaseAmount float64
	// DefaultRate holds the default value on creation for the "rate" field.
	DefaultRate float64
	// DefaultCommissionAmount holds the default value on creation for the "commission_amount" field.
	DefaultCommissionAmount float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralCommission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviterID orders the results by the inviter_id field.
func ByInviterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterID, opts...).ToFunc()
}

// ByDownlineID orders the results by the downline_id field.
func ByDownlineID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownlineID, opts...).ToFunc()
}

// ByTier orders the results by the tier field.
func ByTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTier, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// BySourceRequestID orders the results by the source_request_id field.
func BySourceRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRequestID, opts...).ToFunc()
}

// ByBaseAmount orders the results by the base_amount field.
func ByBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseAmount, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByCommissionAmount orders the results by the commission_amount field.
func ByCommissionAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// BySettledByAdminID orders the results by the settled_by_admin_id field.
func BySettledByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledByAdminID, opts...).ToFunc()
}

// BySettledNote orders the results by the settled_note field.
func BySettledNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
