// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldID, id))
}

// InviterID applies equality check predicate on the "inviter_id" field. It's identical to InviterIDEQ.
func InviterID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviterID, v))
}

// DownlineID applies equality check predicate on the "downline_id" field. It's identical to DownlineIDEQ.
func DownlineID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldDownlineID, v))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldTier, v))
}

// SourceRequestID applies equality check predicate on the "source_request_id" field. It's identical to SourceRequestIDEQ.
func SourceRequestID(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceRequestID, v))
}

// BaseAmount applies equality check predicate on the "base_amount" field. It's identical to BaseAmountEQ.
func BaseAmount(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldBaseAmount, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldRate, v))
}

// CommissionAmount applies equality check predicate on the "commission_amount" field. It's identical to CommissionAmountEQ.
func CommissionAmount(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldStatus, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledAt, v))
}

// SettledByAdminID applies equality check predicate on the "settled_by_admin_id" field. It's identical to SettledByAdminIDEQ.
func SettledByAdminID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledByAdminID, v))
}

// SettledNote applies equality check predicate on the "settled_note" field. It's identical to SettledNoteEQ.
func SettledNote(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// InviterIDEQ applies the EQ predicate on the "inviter_id" field.
func InviterIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviterID, v))
}

// InviterIDNEQ applies the NEQ predicate on the "inviter_id" field.
func InviterIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldInviterID, v))
}

// InviterIDIn applies the In predicate on the "inviter_id" field.
func InviterIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldInviterID, vs...))
}

// InviterIDNotIn applies the NotIn predicate on the "inviter_id" field.
func InviterIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldInviterID, vs...))
}

// InviterIDGT applies the GT predicate on the "inviter_id" field.
func InviterIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldInviterID, v))
}

// InviterIDGTE applies the GTE predicate on the "inviter_id" field.
func InviterIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldInviterID, v))
}

// InviterIDLT applies the LT predicate on the "inviter_id" field.
func InviterIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldInviterID, v))
}

// InviterIDLTE applies the LTE predicate on the "inviter_id" field.
func InviterIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldInviterID, v))
}

// DownlineIDEQ applies the EQ predicate on the "downline_id" field.
func DownlineIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldDownlineID, v))
}

// DownlineIDNEQ applies the NEQ predicate on the "downline_id" field.
func DownlineIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldDownlineID, v))
}

// DownlineIDIn applies the In predicate on the "downline_id" field.
func DownlineIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldDownlineID, vs...))
}

// DownlineIDNotIn applies the NotIn predicate on the "downline_id" field.
func DownlineIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldDownlineID, vs...))
}

// DownlineIDGT applies the GT predicate on the "downline_id" field.
func DownlineIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldDownlineID, v))
}

// DownlineIDGTE applies the GTE predicate on the "downline_id" field.
func DownlineIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldDownlineID, v))
}

// DownlineIDLT applies the LT predicate on the "downline_id" field.
func DownlineIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldDownlineID, v))
}

// DownlineIDLTE applies the LTE predicate on the "downline_id" field.
func DownlineIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldDownlineID, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v int8) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldTier, v))
}

// SourceRequestIDEQ applies the EQ predicate on the "source_request_id" field.
func SourceRequestIDEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceRequestID, v))
}

// SourceRequestIDNEQ applies the NEQ predicate on the "source_request_id" field.
func SourceRequestIDNEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceRequestID, v))
}

// SourceRequestIDIn applies the In predicate on the "source_request_id" field.
func SourceRequestIDIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceRequestID, vs...))
}

// SourceRequestIDNotIn applies the NotIn predicate on the "source_request_id" field.
func SourceRequestIDNotIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceRequestID, vs...))
}

// SourceRequestIDGT applies the GT predicate on the "source_request_id" field.
func SourceRequestIDGT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceRequestID, v))
}

// SourceRequestIDGTE applies the GTE predicate on the "source_request_id" field.
func SourceRequestIDGTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceRequestID, v))
}

// SourceRequestIDLT applies the LT predicate on the "source_request_id" field.
func SourceRequestIDLT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceRequestID, v))
}

// SourceRequestIDLTE applies the LTE predicate on the "source_request_id" field.
func SourceRequestIDLTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceRequestID, v))
}

// SourceRequestIDContains applies the Contains predicate on the "source_request_id" field.
func SourceRequestIDContains(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContains(FieldSourceRequestID, v))
}

// SourceRequestIDHasPrefix applies the HasPrefix predicate on the "source_request_id" field.
func SourceRequestIDHasPrefix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasPrefix(FieldSourceRequestID, v))
}

// SourceRequestIDHasSuffix applies the HasSuffix predicate on the "source_request_id" field.
func SourceRequestIDHasSuffix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasSuffix(FieldSourceRequestID, v))
}

// SourceRequestIDEqualFold applies the EqualFold predicate on the "source_request_id" field.
func SourceRequestIDEqualFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEqualFold(FieldSourceRequestID, v))
}

// SourceRequestIDContainsFold applies the ContainsFold predicate on the "source_request_id" field.
func SourceRequestIDContainsFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContainsFold(FieldSourceRequestID, v))
}

// BaseAmountEQ applies the EQ predicate on the "base_amount" field.
func BaseAmountEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldBaseAmount, v))
}

// BaseAmountNEQ applies the NEQ predicate on the "base_amount" field.
func BaseAmountNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldBaseAmount, v))
}

// BaseAmountIn applies the In predicate on the "base_amount" field.
func BaseAmountIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldBaseAmount, vs...))
}

// BaseAmountNotIn applies the NotIn predicate on the "base_amount" field.
func BaseAmountNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldBaseAmount, vs...))
}

// BaseAmountGT applies the GT predicate on the "base_amount" field.
func BaseAmountGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldBaseAmount, v))
}

// BaseAmountGTE applies the GTE predicate on the "base_amount" field.
func BaseAmountGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldBaseAmount, v))
}

// BaseAmountLT applies the LT predicate on the "base_amount" field.
func BaseAmountLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldBaseAmount, v))
}

// BaseAmountLTE applies the LTE predicate on the "base_amount" field.
func BaseAmountLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldBaseAmount, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldRate, v))
}

// CommissionAmountEQ applies the EQ predicate on the "commission_amount" field.
func CommissionAmountEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionAmount, v))
}

// CommissionAmountNEQ applies the NEQ predicate on the "commission_amount" field.
func CommissionAmountNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCommissionAmount, v))
}

// CommissionAmountIn applies the In predicate on the "commission_amount" field.
func CommissionAmountIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCommissionAmount, vs...))
}

// CommissionAmountNotIn applies the NotIn predicate on the "commission_amount" field.
func CommissionAmountNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCommissionAmount, vs...))
}

// CommissionAmountGT applies the GT predicate on the "commission_amount" field.
func CommissionAmountGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCommissionAmount, v))
}

// CommissionAmountGTE applies the GTE predicate on the "commission_amount" field.
func CommissionAmountGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCommissionAmount, v))
}

// CommissionAmountLT applies the LT predicate on the "commission_amount" field.
func CommissionAmountLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCommissionAmount, v))
}

// CommissionAmountLTE applies the LTE predicate on the "commission_amount" field.
func CommissionAmountLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCommissionAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContainsFold(FieldStatus, v))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldSettledAt))
}

// SettledByAdminIDEQ applies the EQ predicate on the "settled_by_admin_id" field.
func SettledByAdminIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledByAdminID, v))
}

// SettledByAdminIDNEQ applies the NEQ predicate on the "settled_by_admin_id" field.
func SettledByAdminIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSettledByAdminID, v))
}

// SettledByAdminIDIn applies the In predicate on the "settled_by_admin_id" field.
func SettledByAdminIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSettledByAdminID, vs...))
}

// SettledByAdminIDNotIn applies the NotIn predicate on the "settled_by_admin_id" field.
func SettledByAdminIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSettledByAdminID, vs...))
}

// SettledByAdminIDGT applies the GT predicate on the "settled_by_admin_id" field.
func SettledByAdminIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSettledByAdminID, v))
}

// SettledByAdminIDGTE applies the GTE predicate on the "settled_by_admin_id" field.
func SettledByAdminIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSettledByAdminID, v))
}

// SettledByAdminIDLT applies the LT predicate on the "settled_by_admin_id" field.
func SettledByAdminIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSettledByAdminID, v))
}

// SettledByAdminIDLTE applies the LTE predicate on the "settled_by_admin_id" field.
func SettledByAdminIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSettledByAdminID, v))
}

// SettledByAdminIDIsNil applies the IsNil predicate on the "settled_by_admin_id" field.
func SettledByAdminIDIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldSettledByAdminID))
}

// SettledByAdminIDNotNil applies the NotNil predicate on the "settled_by_admin_id" field.
func SettledByAdminIDNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldSettledByAdminID))
}

// SettledNoteEQ applies the EQ predicate on the "settled_note" field.
func SettledNoteEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledNote, v))
}

// SettledNoteNEQ applies the NEQ predicate on the "settled_note" field.
func SettledNoteNEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSettledNote, v))
}

// SettledNoteIn applies the In predicate on the "settled_note" field.
func SettledNoteIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSettledNote, vs...))
}

// SettledNoteNotIn applies the NotIn predicate on the "settled_note" field.
func SettledNoteNotIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSettledNote, vs...))
}

// SettledNoteGT applies the GT predicate on the "settled_note" field.
func SettledNoteGT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSettledNote, v))
}

// SettledNoteGTE applies the GTE predicate on the "settled_note" field.
func SettledNoteGTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSettledNote, v))
}

// SettledNoteLT applies the LT predicate on the "settled_note" field.
func SettledNoteLT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSettledNote, v))
}

// SettledNoteLTE applies the LTE predicate on the "settled_note" field.
func SettledNoteLTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSettledNote, v))
}

// SettledNoteContains applies the Contains predicate on the "settled_note" field.
func SettledNoteContains(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContains(FieldSettledNote, v))
}

// SettledNoteHasPrefix applies the HasPrefix predicate on the "settled_note" field.
func SettledNoteHasPrefix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasPrefix(FieldSettledNote, v))
}

// SettledNoteHasSuffix applies the HasSuffix predicate on the "settled_note" field.
func SettledNoteHasSuffix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasSuffix(FieldSettledNote, v))
}

// SettledNoteIsNil applies the IsNil predicate on the "settled_note" field.
func SettledNoteIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldSettledNote))
}

// SettledNoteNotNil applies the NotNil predicate on the "settled_note" field.
func SettledNoteNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldSettledNote))
}

// SettledNoteEqualFold applies the EqualFold predicate on the "settled_note" field.
func SettledNoteEqualFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEqualFold(FieldSettledNote, v))
}

// SettledNoteContainsFold applies the ContainsFold predicate on the "settled_note" field.
func SettledNoteContainsFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContainsFold(FieldSettledNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.NotPredicates(p))
}
